In [9]:
myDictionary = {"Hello":{"Test": "Case", "Mount": "Blau"}}

In [11]:
print(myDictionary["Hello"]["Mount"])

Blau


# Iteration / continue / break 

In [19]:
ml = [0,1,2,3,4,5,67,7,8]


for i in range(0, len(ml), 3):
    print(ml[i])

0
3
67


In [24]:
myDict = {"Name": "tom", "age": 16}
for key in myDict:
    print(key)

Name
age


In [30]:
for value in myDict.values():
    if value == "tom":
        continue # skipping the step
#        break # completely stop iteration
    print(value)

16


# numpy

In [32]:
import numpy as np

In [36]:
test = np.ones((2,3))

print (test)

[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
myarray = np.array([1,2,3,4])

print(myarray)

[1 2 3 4]


In [44]:
myarray = np.array(np.arange(10,20))
print(myarray)

[10 11 12 13 14 15 16 17 18 19]


In [45]:
myarray = np.array(np.arange(10,20)) * 2 # every entry *2
print(myarray)

[20 22 24 26 28 30 32 34 36 38]


In [53]:
# multidemensional array

arrayTwo = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print(arrayTwo)

print("dimesnsions: ", arrayTwo.shape)

# when shape (3, ) => it is a vector

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimesnsions:  (3, 3)


In [58]:
arr = np.array(np.arange(1,10)).reshape(3,3)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:

print("Max: ", arr.max())
print("Min: ", arr.min())
print("Avg: ", np.mean(arr))

Max:  9
Min:  1
Avg:  5.0


In [65]:
mask  = arr > 5
print(mask)

print("-----")
print(arr[mask])

[[False False False]
 [False False  True]
 [ True  True  True]]
-----
[6 7 8 9]


In [70]:
print("first three", arr[0:1:, 0:1:1])

# Would be great to practice slicing more

first three [[1]]


In [81]:
arr1 = np.array(np.arange(1,17)).reshape(4,4)
arr2 = np.array(np.arange(17,33)).reshape(4,4)

print(arr1 * arr2) # dot product
print(arr1 @ arr2) # matrix multiply
print(np.matmul(arr1,arr2)) # same as above

[[ 17  36  57  80]
 [105 132 161 192]
 [225 260 297 336]
 [377 420 465 512]]
[[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]
[[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]


# Slicing practice

In [131]:
testArr = np.array(np.arange(0,9)).reshape(3,3)
print(testArr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [132]:
# get first two entries of first two rows

print(testArr[0:2, 0:2])

[[0 1]
 [3 4]]


In [133]:
# get all outer corner numbers

print(testArr[0::2, 0::2])

[[0 2]
 [6 8]]


In [143]:
# just extract the middle row
print(testArr[0:, 1:-1])

[[1]
 [4]
 [7]]


In [122]:
testArr = np.array(np.arange(0,10))
print(testArr)

[0 1 2 3 4 5 6 7 8 9]


In [125]:
# get all even numbers
print(testArr[0::2])

[0 2 4 6 8]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# OOP

In [98]:
class Animal:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def voice(self):
        print(self.name, "sounds it's voice")

In [99]:
a1 = Animal("Tony", 29)

a1.voice()

Tony sounds it's voice
